version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5

    working_directory: ~/repo
    steps:
      - checkout

      - run: sudo apt-get install libblas-dev libsvm-dev
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: rm deps/xxhash/c_src/*.o
      - run: mix test
      - run: mix dialyzer --halt-exit-status
      - run: mix credo --strict
